# Generated by Django 3.2.4 on 2021-08-30 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_product_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table', models.CharField(max_length=100)),
                ('node', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=100)),
                ('truncate', models.BooleanField()),
            ],
        ),
    ]
